map_download:
  distance: 150
  network_type: drive
map_search:
  bbox_size: 150
  default_city: San Francisco
  max_results: 5
output:
  base_dir: output
  scene_prefix: scene_
sumo:
  begin_time: 0
  end_time: 3600
traffic:
  end_time: 3600
  vehicle_period: 0.5
visualization:
  preview:
    dpi: 300
    enabled: true
    figure_height: 8
    figure_width: 16
    interactive_map: true
    randomize:
      enabled: true
      map_style: true
      node_selection: true
      seed: 0
      visualization: true
    satellite_view: true
